groups:
  - name: code-nest-alerts
    interval: 30s
    rules:
      # JVM 内存使用率告警
      - alert: HighMemoryUsage
        expr: (jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"}) > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "JVM堆内存使用率过高"
          description: "{{ $labels.application }} 堆内存使用率超过90%，当前值：{{ $value }}"
      
      # HTTP 错误率告警
      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "HTTP 5xx错误率过高"
          description: "{{ $labels.application }} 5xx错误率超过5%"
      
      # 数据库连接池告警
      - alert: DatabaseConnectionPoolExhausted
        expr: hikaricp_connections_pending > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "数据库连接池耗尽"
          description: "{{ $labels.application }} 有{{ $value }}个请求在等待数据库连接"
      
      # 应用停止响应告警
      - alert: ApplicationDown
        expr: up{job="code-nest"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "应用停止响应"
          description: "{{ $labels.application }} 无法访问，可能已停止运行"
      
      # GC 时间过长告警
      - alert: HighGCTime
        expr: rate(jvm_gc_pause_seconds_sum[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "GC时间占比过高"
          description: "{{ $labels.application }} GC时间占比超过10%"
      
      # CPU 使用率告警
      - alert: HighCPUUsage
        expr: process_cpu_usage > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "CPU使用率过高"
          description: "{{ $labels.application }} CPU使用率超过80%，当前值：{{ $value }}"
      
      # 慢请求告警
      - alert: SlowRequests
        expr: histogram_quantile(0.99, rate(http_server_requests_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "接口响应时间过长"
          description: "{{ $labels.application }} P99响应时间超过2秒"

