# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /uapi
spring:
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  mvc:
    # 设置静态资源路径 防止所有请求都去查静态资源
    static-path-pattern: /static/**
thread-pool:
  # 是否开启线程池
  enabled: true
dromara:
  x-file-storage: #文件存储配置
    default-platform: tencent-cos-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    tencent-cos: #腾讯云cos配置
      - platform: tencent-cos-1 #平台标识
        enable-storage: true  # 启用存储
        secret-id: AKIDYzDG8oGX2PZdU8YkjV4PXSCj393jKisF
        secret-key: Y6VhhXAdtwlOo0zlJl26wZzBAvTnxtc7
        region: ap-chengdu #存仓库所在地域
        bucket-name: 11-1305448902
        domain: https://11-1305448902.cos.ap-chengdu.myqcloud.com/ # 访问域名，注意“/”结尾，例如：https://abc.cos.ap-nanjing.myqcloud.com/
        base-path: upload/ # 基础路径


