# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    context-path: /uapi
spring:
  config:
    #这里里面放着一些私密的不能开源的配置
    import: "optional:application-sec.yml"
  profiles:
    active: dev
  application:
    name: U-Space-2.X
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
sa-token:
  # token 有效期（单位：秒），默认30天，-1代表永不过期
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1

sse:
  enabled: true
  path: /resource/sse
mybatis-plus:
  type-handlers-package: com.xiaou.mybatis.handler


xxl:
  job:
    admin-addresses: http://localhost:8081/xxl-job-admin
    app-name: my-app
    ip: 127.0.0.1
    access-token: default_token
    enabled: false
