-- SQL监控日志表
CREATE TABLE IF NOT EXISTS `sql_monitor_log` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `trace_id` VARCHAR(32) NOT NULL COMMENT '跟踪ID',
    `user_id` BIGINT COMMENT '用户ID',
    `user_type` VARCHAR(10) COMMENT '用户类型 (admin/user)',
    `username` VARCHAR(50) COMMENT '用户名',
    `request_ip` VARCHAR(45) COMMENT '请求IP',
    `request_uri` VARCHAR(500) COMMENT '请求URI',
    `http_method` VARCHAR(10) COMMENT 'HTTP方法',
    `module` VARCHAR(50) COMMENT '操作模块',
    `method` VARCHAR(100) COMMENT '操作方法',
    `mapper_method` VARCHAR(200) NOT NULL COMMENT 'MyBatis Mapper方法',
    `sql_statement` TEXT NOT NULL COMMENT 'SQL语句',
    `sql_type` VARCHAR(10) NOT NULL COMMENT 'SQL类型 (SELECT/INSERT/UPDATE/DELETE)',
    `sql_params` TEXT COMMENT 'SQL参数',
    `execution_time` BIGINT NOT NULL COMMENT '执行时间(毫秒)',
    `affected_rows` INT DEFAULT 0 COMMENT '影响行数',
    `success` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否成功',
    `error_message` TEXT COMMENT '错误信息',
    `slow_sql` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否慢SQL',
    `execute_time` DATETIME NOT NULL COMMENT '执行时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    INDEX `idx_trace_id` (`trace_id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_user_type` (`user_type`),
    INDEX `idx_username` (`username`),
    INDEX `idx_module` (`module`),
    INDEX `idx_sql_type` (`sql_type`),
    INDEX `idx_slow_sql` (`slow_sql`),
    INDEX `idx_success` (`success`),
    INDEX `idx_execute_time` (`execute_time`),
    INDEX `idx_create_time` (`create_time`),
    INDEX `idx_execution_time` (`execution_time`),
    INDEX `idx_mapper_method` (`mapper_method`(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SQL监控日志表';
